# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Mise_en_page_Enercoop
                                 A QGIS plugin
 Un plugin permettant de faire des sorties de mise en page automatique
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-04-26
        copyright            : (C) 2023 by Jumeau-Mousset Lucas
        email                : lucas.jumeau-mousset@enercoop.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jumeau-Mousset Lucas'
__date__ = '2023-04-26'
__copyright__ = '(C) 2023 by Jumeau-Mousset Lucas'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterString,
                       QgsProcessingParameterFolderDestination)
from qgis import processing


class Mise_en_page_EnercoopAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    TYPE = 'TYPE'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Mise en page Enercoop'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Mise_en_page_EnercoopAlgorithm()

    def initAlgorithm(self, config=None):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterEnum(
                self.INPUT,
                self.tr('Selection de la mise en page'),
                options=['Environnement', 'Localisation'],
                allowMultiple=False

            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.TYPE,
                self.tr('Type de document'),
                options=['pdf', 'png'],
                allowMultiple=False

            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFolderDestination(
                self.OUTPUT,
                self.tr('Dossier de sortie')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        """
        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}"""

        layout_option = self.parameterAsEnumString(parameters, self.INPUT, context)
        type_option = self.parameterAsEnumString(parameters, self.TYPE, context)
        
        if layout_option == 0:
            layout_option = 'Environnement'
        elif layout_option == 1:
            layout_option = 'Localisation'
        else:
            layout_option = 'Environnement'

        export_atlas_png = processing.run("native:atlaslayouttoimage",
                                    {'LAYOUT':layout_option,
                                    'COVERAGE_LAYER':None,
                                    'FILTER_EXPRESSION':'is_selected()',
                                    'SORTBY_EXPRESSION':'',
                                    'SORTBY_REVERSE':False,
                                    'FILENAME_EXPRESSION':"'output_'||@atlas_featurenumber",
                                    'FOLDER':self.OUTPUT,
                                    'LAYERS':None,
                                    'EXTENSION':8,
                                    'DPI':None,
                                    'GEOREFERENCE':True,
                                    'INCLUDE_METADATA':True,
                                    'ANTIALIAS':True})
        
        export_atlas_pdf = processing.run("native:atlaslayouttomultiplepdf",
                                    {'LAYOUT': layout_option,
                                    'COVERAGE_LAYER': None,
                                    'FILTER_EXPRESSION': 'is_selected()',
                                    'SORTBY_EXPRESSION': '',
                                    'SORTBY_REVERSE': False,
                                    'LAYERS': None,
                                    'DPI': None,
                                    'FORCE_VECTOR': False,
                                    'FORCE_RASTER': False,
                                    'GEOREFERENCE': True,
                                    'INCLUDE_METADATA': True,
                                    'DISABLE_TILED': False,
                                    'SIMPLIFY': True,
                                    'TEXT_FORMAT': 0,
                                    'IMAGE_COMPRESSION': 0,
                                    'OUTPUT_FILENAME': '',
                                    'OUTPUT_FOLDER': self.OUTPUT})

        if type_option == 0:
            return export_atlas_pdf
        elif type_option ==  1:
            return export_atlas_png
        else:
            return export_atlas_pdf        