# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Mise_en_page_Enercoop
                                 A QGIS plugin
 Un plugin permettant de faire des sorties de mise en page automatique
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-04-26
        copyright            : (C) 2023 by Jumeau-Mousset Lucas
        email                : lucas.jumeau-mousset@enercoop.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jumeau-Mousset Lucas'
__date__ = '2023-04-26'
__copyright__ = '(C) 2023 by Jumeau-Mousset Lucas'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterString,
                       QgsProcessingParameterFolderDestination,
                       QgsProcessingParameterBoolean,
                       QgsProcessingFeedback,
                       QgsProcessingParameterVectorLayer)
from qgis import processing


class Mise_en_page_EnercoopAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    INPUT_VECTOR = 'INPUT_VECTOR'
    TYPE = 'TYPE'
    SELECT = 'SELECT'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Mise en page Enercoop'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Mise_en_page_EnercoopAlgorithm()

    def initAlgorithm(self, config=None):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT_VECTOR,
                self.tr('Choose vector layer as input'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.SELECT,
                self.tr('Traiter uniquement les entités sélectionnées')

            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.INPUT,
                self.tr('Selection de la mise en page'),
                options=['Environnement', 'Localisation'],
                allowMultiple=False

            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.TYPE,
                self.tr('Type de document'),
                options=['pdf', 'png'],
                allowMultiple=False

            )
        )

        self.addParameter(
            QgsProcessingParameterFolderDestination(
                self.OUTPUT,
                self.tr('Dossier de sortie')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):

        log = feedback.setProgressText

        layout_option = self.parameterAsEnum(parameters, self.INPUT, context)
        type_option = self.parameterAsEnum(parameters, self.TYPE, context)
        select_option = self.parameterAsBool(parameters, self.SELECT, context)
        input_vector = self.parameterAsVectorLayer(parameters, self.INPUT_VECTOR, context)

        if layout_option == 0:
            layout_option = 'Environnement'
        elif layout_option == 1:
            layout_option = 'Localisation'
        else:
            layout_option = 'Environnement'

        if select_option == True:
            select_option = 'is_selected()'
        elif select_option == False:
            select_option = ''
        else:
            select_option = ''

        if type_option == 1:
            export_image = processing.run("native:atlaslayouttoimage",
                                        {'LAYOUT':layout_option,
                                        'COVERAGE_LAYER':input_vector,
                                        'FILTER_EXPRESSION':select_option,
                                        'SORTBY_EXPRESSION':'',
                                        'SORTBY_REVERSE':False,
                                        'FILENAME_EXPRESSION':"'output_'||@atlas_featurenumber",
                                        'FOLDER':self.OUTPUT,
                                        'LAYERS':None,
                                        'EXTENSION':8,
                                        'DPI':None,
                                        'GEOREFERENCE':True,
                                        'INCLUDE_METADATA':True,
                                        'ANTIALIAS':True})
            return export_image
        elif type_option == 0:
            export_pdf = processing.run("native:atlaslayouttomultiplepdf",
                                        {'LAYOUT': layout_option,
                                        'COVERAGE_LAYER': input_vector,
                                        'FILTER_EXPRESSION': select_option,
                                        'SORTBY_EXPRESSION': '',
                                        'SORTBY_REVERSE': False,
                                        'LAYERS': None,
                                        'DPI': None,
                                        'FORCE_VECTOR': False,
                                        'FORCE_RASTER': False,
                                        'GEOREFERENCE': True,
                                        'INCLUDE_METADATA': True,
                                        'DISABLE_TILED': False,
                                        'SIMPLIFY': True,
                                        'TEXT_FORMAT': 0,
                                        'IMAGE_COMPRESSION': 0,
                                        'OUTPUT_FILENAME': '',
                                        'OUTPUT_FOLDER': self.OUTPUT})
            return export_pdf
        else: ''
